version: "3.9"

services: 
  web:
    build: .
    ports: 
      - "3000:3000"
    environment:
      - PORT=5000
      - "REDIS_URL=redis://redis:6379/0"
      - "MONGODB_URL=mongodb://mongo:27017/0"
